export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'About',
  headline: 'This is the About headline',
  description: 'A detail-oriented Full Stack Web Developer with a knack for delivering user-friendly solutions effectively and efficiently. Possesses a track record of developing frontend web applications, secure backend databases and fully-functional websites both self-created and with team members. Regular participant of local hackathons and web developer meetups. Consistantly learning and improving design and coding skills, while looking for innovative ways to enhance production. Enjoys helping clients to achieve their desired look and database functionality for their online business.',
  buttonLabel: 'See Projects',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'about-image',
  dark: true,
  primary: true,
  darkText: false,
}

export const homeObjTwo = {
  id: 'portfolio',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Portfolio',
  headline: 'This is the Portfolio headline',
  description: 'A detail-oriented Full Stack Web Developer with a knack for delivering user-friendly solutions effectively and efficiently. Possesses a track record of developing frontend web applications, secure backend databases and fully-functional websites both self-created and with team members. Regular participant of local hackathons and web developer meetups. Consistantly learning and improving design and coding skills, while looking for innovative ways to enhance production. Enjoys helping clients to achieve their desired look and database functionality for their online business.',
  buttonLabel: 'Learn More',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'portfolio-image',
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: 'resume',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Resume',
  headline: 'This is the Resume headline',
  description: 'A detail-oriented Full Stack Web Developer with a knack for delivering user-friendly solutions effectively and efficiently. Possesses a track record of developing frontend web applications, secure backend databases and fully-functional websites both self-created and with team members. Regular participant of local hackathons and web developer meetups. Consistantly learning and improving design and coding skills, while looking for innovative ways to enhance production. Enjoys helping clients to achieve their desired look and database functionality for their online business.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'resume-image',
  dark: true,
  primary: true,
  darkText: false,
}