export const homeObjOne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'About',
  headline: 'Full Stack Web Developer',
  description: 'A detail-oriented Full Stack Web Developer with a knack for delivering user-friendly solutions effectively and efficiently. Specializes in building applications with the MERN stack. Possesses a track record of developing frontend web applications, secure backend databases and fully-functional websites both self-created and with team members. Regular participant of local hackathons and web developer meetups. Consistantly learning and improving design and coding skills, while looking for innovative ways to enhance production. Enjoys helping clients to achieve their desired look and database functionality for their online business.',
  buttonLabel: 'See Projects',
  buttonLocation: 'portfolio',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'about-image',
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjTwo = {
  id: 'portfolio',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Portfolio',
  headline: 'This is the Portfolio headline',
  buttonLabel: 'Learn More',
  buttonLocation: '',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'portfolio-image',
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: 'resume',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Resume',
  headline: 'Lambda School Graduate',
  description: 'Lambda School is a 9+ month computer science & software engineering program that provides an immersive hands-on curriculum with a focus on computer science, and full-stack web development. For more information about my work experience, please view my LinkedIn profile.',
  buttonLabel: 'Social Media Links',
  buttonLocation: 'footer',
  imgStart: true,
  img: require('../../images/svg-1.svg').default,
  alt: 'resume-image',
  dark: false,
  primary: false,
  darkText: true,
}